[global]
developmentMode = false

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#00ff41"
backgroundColor = "#0c0c0c"
secondaryBackgroundColor = "#1a1a2e"
textColor = "#00ff41" 